name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build Project
      run: |
        dotnet restore src/Mappy/Mappy.csproj
        dotnet build src/Mappy/Mappy.csproj

    - name: Pack the project as a NuGet package
      run: |
        dotnet pack src/Mappy/Mappy.csproj -c Release -o artifacts

    - name: Publish to GitHub Packages
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push artifacts/*.nupkg --source ${{ secrets.NUGET_SOURCE }}
