name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  pack:
    name: Pack NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore src/Mappy/Mappy.csproj

      - name: Build
        run: dotnet build src/Mappy/Mappy.csproj \
          --configuration Release \
          --no-restore

      - name: Pack
        run: dotnet pack src/Mappy/Mappy.csproj \
          --configuration Release \
          --no-build \
          --no-restore \
          -o artifacts

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: artifacts/*.nupkg
          if-no-files-found: error
